const wilayaOptions = [
  { label: "Adrar", value: 1 },
  { label: "Chlef", value: 2 },
  { label: "Laghouat", value: 3 },
  { label: "Oum El Bouaghi", value: 4 },
  { label: "Batna", value: 5 },
  { label: "Béjaïa", value: 6 },
  { label: "Biskra", value: 7 },
  { label: "Béchar", value: 8 },
  { label: "Blida", value: 9 },
  { label: "Bouira", value: 10 },
  { label: "Tamanrasset", value: 11 },
  { label: "Tébessa", value: 12 },
  { label: "Tlemcen", value: 13 },
  { label: "Tiaret", value: 14 },
  { label: "Tizi Ouzou", value: 15 },
  { label: "Alger", value: 16 },
  { label: "Djelfa", value: 17 },
  { label: "Jijel", value: 18 },
  { label: "Sétif", value: 19 },
  { label: "Saïda", value: 20 },
  { label: "Skikda", value: 21 },
  { label: "Sidi Bel Abbès", value: 22 },
  { label: "Annaba", value: 23 },
  { label: "Guelma", value: 24 },
  { label: "Constantine", value: 25 },
  { label: "Médéa", value: 26 },
  { label: "Mostaganem", value: 27 },
  { label: "M'Sila", value: 28 },
  { label: "Mascara", value: 29 },
  { label: "Ouargla", value: 30 },
  { label: "Oran", value: 31 },
  { label: "El Bayadh", value: 32 },
  { label: "Illizi", value: 33 },
  { label: "Bordj Bou Arreridj", value: 34 },
  { label: "Boumerdès", value: 35 },
  { label: "El Tarf", value: 36 },
  { label: "Tindouf", value: 37 },
  { label: "Tissemsilt", value: 38 },
  { label: "El Oued", value: 39 },
  { label: "Khenchela", value: 40 },
  { label: "Souk Ahras", value: 41 },
  { label: "Tipaza", value: 42 },
  { label: "Mila", value: 43 },
  { label: "Aïn Defla", value: 44 },
  { label: "Naâma", value: 45 },
  { label: "Témouchent", value: 46 },
  { label: "Ghardaïa", value: 47 },
  { label: "Relizane", value: 48 }
];

export default wilayaOptions;
